version: "2.1"
services:
  mongo:
    image: mongo:3.2.4
    ports:
      - 27017:27017

  spring-boot-mongo-docker:
    build: .
    ports:
      - 8080:8080
    links:
      - mongo
    entrypoint: "java -Dspring.data.mongodb.uri=mongodb://mongo:27017/surveydb -Djava.security.egd=file:/dev/./urandom -jar /app.jar"